# Generated by Django 3.2.6 on 2021-08-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_puppy'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='coat_type',
            field=models.CharField(default='coat length', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puppy',
            name='color',
            field=models.CharField(default='color', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puppy',
            name='comments',
            field=models.CharField(default='comments about puppy here', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puppy',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puppy',
            name='photo',
            field=models.ImageField(default='image here', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puppy',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
