# Generated by Django 3.2.6 on 2021-08-11 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='breeder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=40)),
                ('coat_type', models.CharField(max_length=40)),
                ('comments', models.CharField(max_length=400)),
                ('photo', models.ImageField(upload_to='')),
                ('breeder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
