# Generated by Django 3.2.6 on 2021-08-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210811_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True),
        ),
    ]
