# Generated by Django 3.2.6 on 2021-08-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210811_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Breeder'), (2, 'Puppy Parent')], null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='allergies',
            field=models.CharField(default='Vaccines here', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccine_status',
            field=models.CharField(choices=[('Rabies', 'Rabies'), ('Parvo', 'Parvo'), ('Distemper', 'Distemper'), ('Bordetella', 'Bordetella'), ('Hepatitis', 'Hepatitis'), ('Influenza', 'Influenza'), ('Heartworm', 'Heartworm'), ('Leptospirosis', 'Leptospirosis'), ('Lyme Disease', 'Lyme Disease')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Puppy',
        ),
    ]
