# Generated by Django 3.2.6 on 2021-08-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210812_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Breeder'), (2, 'Puppy Parent (Adopter)')], null=True),
        ),
    ]
