# Generated by Django 3.2.6 on 2021-08-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_number_of_dogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
