# Generated by Django 3.2.6 on 2021-08-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_dog_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
