# Generated by Django 3.2.6 on 2021-08-18 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_dog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='allergies',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dog',
            name='coat_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='dog',
            name='comments',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='vaccine_status',
            field=models.CharField(blank=True, choices=[('Rabies', 'Rabies'), ('Parvo', 'Parvo'), ('Distemper', 'Distemper'), ('Bordetella', 'Bordetella'), ('Hepatitis', 'Hepatitis'), ('Influenza', 'Influenza'), ('Heartworm', 'Heartworm'), ('Leptospirosis', 'Leptospirosis'), ('Lyme Disease', 'Lyme Disease')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
