# Generated by Django 3.2.6 on 2021-08-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210818_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
