# Generated by Django 3.2.6 on 2021-08-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_dog_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
