# Generated by Django 3.2.6 on 2021-08-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_dog_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('BREEDER', 'Breeder'), ('PUPPY PARENT', 'Puppy Parent (Adopter)')], null=True),
        ),
    ]
