# Generated by Django 3.2.6 on 2021-08-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Breeder'), (2, 'Puppy Parent (Adopter)')], null=True),
        ),
    ]
