# Generated by Django 3.2.6 on 2021-08-19 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breeder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
