# Generated by Django 3.2.6 on 2021-08-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210819_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number_of_dogs',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
